package Constants;

import java.util.ArrayList;
import java.util.List;

public class Chords {
    public static String[] Chords= new String[]{
            new String("Cmaj7"),
            new String("Cmaj4"),
            new String("Cmaj0"),
            new String("Cmaj"),
            new String("Gmaj"),
            new String("Amaj"),
            new String("Bmaj"),
            new String("Dmaj"),
            new String("Emaj"),
            new String("Fmaj"),
            new String("Cmin0"),
            new String("Cmin3"),
            new String("Cmin7"),
            new String("Cmin"),
            new String("Gmin"),
            new String("Amin"),
            new String("Bmin"),
            new String("Dmin"),
            new String("Emin"),
            new String("Fmin"),
            new String("Caug0"),
            new String("Caug4"),
            new String("Caug8"),
            new String("Cdim0"),
            new String("Cdim3"),
            new String("Cdim6"),
            new String("Cdom70"),
            new String("Cdom74"),
            new String("Cdom77"),
            new String("Cdom710"),
            new String("Cmaj70"),
            new String("Cmaj74"),
            new String("Cmaj77"),
            new String("Cmaj711"),
            new String("Cmin70"),
            new String("Cmin73"),
            new String("Cmin77"),
            new String("Cmin710"),
            new String("Csus40"),
            new String("Csus45"),
            new String("Csus47"),
            new String("Csus20"),
            new String("Csus22"),
            new String("Csus27"),
            new String("Cmaj60"),
            new String("Cmaj64"),
            new String("Cmaj67"),
            new String("Cmaj69"),
            new String("Cmin60"),
            new String("Cmin63"),
            new String("Cmin67"),
            new String("Cmin69"),
            new String("Cdom90"),
            new String("Cdom94"),
            new String("Cdom97"),
            new String("Cdom910"),
            new String("Cdom914"),
            new String("Cmaj90"),
            new String("Cmaj94"),
            new String("Cmaj97"),
            new String("Cmaj911"),
            new String("Cmaj914")
    };

}
